language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: "node"
env:
  - EXTENSION_ID=bgbhfmeabcmpjblimfddkeikogidjhao
before_script:
  - npm prune
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true
